'use client';

import { TrendingUp, TrendingDown, Minus } from 'lucide-react';
import { format } from 'date-fns';
import type { PredictionSummary, Prediction } from '@/lib/api';

interface PredictionPanelProps {
  predictions: PredictionSummary;
  currentPrice: number;
}

interface PredictionCardProps {
  prediction: Prediction;
  currentPrice: number;
  title: string;
}

function PredictionCard({ prediction, currentPrice, title }: PredictionCardProps) {
  const getDirectionIcon = (direction: string) => {
    switch (direction) {
      case 'UP':
        return <TrendingUp className="w-8 h-8 text-emerald-500" />;
      case 'DOWN':
        return <TrendingDown className="w-8 h-8 text-red-500" />;
      default:
        return <Minus className="w-8 h-8 text-slate-500" />;
    }
  };

  const getChangeColor = (change: number) => {
    if (change > 0) return 'text-emerald-500';
    if (change < 0) return 'text-red-500';
    return 'text-slate-400';
  };

  const confidencePercentage = (prediction.confidence * 100).toFixed(0);

  return (
    <div className="bg-slate-800 rounded-lg p-6 border border-slate-700">
      <div className="flex items-center justify-between mb-4">
        <h3 className="text-lg font-semibold text-white">{title}</h3>
        {getDirectionIcon(prediction.predicted_direction)}
      </div>

      <div className="space-y-4">
        {/* Predicted Change */}
        <div>
          <p className="text-slate-400 text-sm">Predicted Change</p>
          <p className={`text-3xl font-bold ${getChangeColor(prediction.predicted_change)}`}>
            {prediction.predicted_change > 0 ? '+' : ''}{prediction.predicted_change.toFixed(2)}%
          </p>
        </div>

        {/* Predicted Price */}
        <div>
          <p className="text-slate-400 text-sm">Target Price</p>
          <p className="text-2xl font-semibold text-white">
            ₹{prediction.predicted_price.toFixed(2)}
          </p>
        </div>

        {/* Confidence */}
        <div>
          <div className="flex items-center justify-between mb-2">
            <p className="text-slate-400 text-sm">Confidence</p>
            <p className="text-white font-semibold">{confidencePercentage}%</p>
          </div>
          <div className="w-full bg-slate-700 rounded-full h-2">
            <div
              className="bg-emerald-500 h-2 rounded-full transition-all"
              style={{ width: `${confidencePercentage}%` }}
            ></div>
          </div>
        </div>

        {/* Target Date */}
        <div>
          <p className="text-slate-400 text-sm">Target Date</p>
          <p className="text-white">
            {format(new Date(prediction.target_date), 'MMM dd, yyyy')}
          </p>
        </div>

        {/* Model Info */}
        <div className="pt-4 border-t border-slate-700">
          <p className="text-slate-400 text-xs">
            Model: {prediction.model_name.toUpperCase()} • 
            Predicted on {format(new Date(prediction.prediction_date), 'MMM dd')}
          </p>
        </div>
      </div>
    </div>
  );
}

export default function PredictionPanel({ predictions, currentPrice }: PredictionPanelProps) {
  return (
    <div className="space-y-6">
      <h2 className="text-2xl font-bold text-white">AI Predictions</h2>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Next Day Prediction */}
        {predictions.next_day && (
          <PredictionCard
            prediction={predictions.next_day}
            currentPrice={currentPrice}
            title="Next Day Prediction"
          />
        )}

        {/* Next Week Prediction */}
        {predictions.next_week && (
          <PredictionCard
            prediction={predictions.next_week}
            currentPrice={currentPrice}
            title="Next Week Prediction"
          />
        )}
      </div>

      {/* Disclaimer */}
      <div className="bg-slate-800 border border-slate-700 rounded-lg p-4">
        <p className="text-slate-400 text-sm">
          <strong className="text-white">Disclaimer:</strong> These predictions are generated by machine learning models
          for educational purposes only. They should not be considered as financial advice. Always do your own research
          and consult with a financial advisor before making investment decisions.
        </p>
      </div>
    </div>
  );
}
